### ISSUE TITLE
Fix the build/check confusion for npm/yarn projects

### ISSUE THREAD

**Issue by jkarni** [garnix-io/garn#230]
Currently the `testCommand` is the only thing in the build, and there is no test. This is very confusing. The test should be a check (obvi), and moreover the build should build. 

```[tasklist]
### Tasks
- [ ] https://github.com/garnix-io/garn/pull/235
- [ ] https://github.com/garnix-io/garn/issues/255
```

**Comment by soenkehahn** [comment]
After #235 is merged `mkNpmProject` should make more sense with regards to `Check`s. We got rid of `testCommand` and users have to specify additional `Check`s with `addCheck`.

Regarding building: It's not very clear what a package for an npm project would be, since people will want to use different bundlers or no bundler at all. I opened #255 to tackle that.

Regarding `mkYarnProject`: I think we should focus on `mkNpmProject` for now. And then either remove `mkYarnProject` before release or -- if we care and find the time -- align it with `mkNpmProject`.
