### ISSUE TITLE
installation on nixos fails stating Read-only file system

### ISSUE THREAD

**Issue by KiaraGrouwstra** [garnix-io/garn#402]
```
$ sh <(curl --proto '=https' --tlsv1.2 -sSf https://garn.io/install.sh)

NIX INSTALLATION
================
Hooray, nix is already installed:
nix (Nix) 2.17.1

BINARY CACHE CONFIGURATION
==========================
For 'garn' to work well, nix needs to use the garnix.io binary
cache. But the cache configuration cannot be found. This
installer will modify /etc/nix/nix.conf to add the garnix.io binary cache.

Should I add the garnix.io binary cache to /etc/nix/nix.conf now (requires sudo)? [y/n] y
tee: /etc/nix/nix.conf: Read-only file system
```

i see it's mentioning needing `sudo`, but given that as-is this fails perhaps the documentation could be adjusted a bit to reflect this - prepending `sh` with `sudo` appears not to help fix the command.

**Comment by jkarni** [comment]
Thanks for the report! Are you on NixOS? I can see how that would fail there, since it’s generated by configuration.nix, and we should really fix that!

**Comment by KiaraGrouwstra** [comment]
@jkarni yeah i'm on nixos

**Comment by jkarni** [comment]
As a workaround you can manually add https://cache.garnix.io to substituters, and cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g= to trusted-public-keys in your configuration.nix and doing a NixOS-rebuild, or to ~/.config/nix/nix.conf if you are a trusted user in the global nix config. 

As a more proper solution for the install script I’m not sure what we should do. I’m inclined to say we should add the config to the user nix.conf if the user is a trusted user, and otherwise just print instructions, since doing a NixOS rebuild for the user is not a good idea.

**Comment by soenkehahn** [comment]
I'm not sure what the best fix is here. We could do what @jkarni suggested and check for whether the user is a [trusted user](https://nixos.org/manual/nix/stable/command-ref/conf-file.html?highlight=trusted%20user#conf-trusted-users). And then try to add the config lines to the user's config. But what if they aren't? Or what if they are, but their user config is also read-only, since it's managed by [home-manager](https://nix-community.github.io/home-manager/)? Also, I think, on a standard nixos install normal users are *not* trusted users, so it would only help a small subset of users.

In any case, as a first step, I think the install script should give a much better error message, including a pointer to some documentation about how to add the cache to the config manually. I created https://github.com/garnix-io/garn/issues/408 for that.

@KiaraGrouwstra: Thanks for reporting! Did you try to manually add the cache? We have some documentation about it [on the garnix website](https://garnix.io/docs/caching) and on [the garn website](https://garn.io/docs/getting_started#manual-installation). I know this isn't a proper fix, but afterwards you could try out the installer again, and hopefully it would work.

**Comment by alexdavid** [comment]
We added an error message in garn v0.0.19 that should be more helpful when installing on NixOS since the installer cannot modify your configuration. I'm going to close this issue for now but feel free to re-open if there is still an issue.
